{% set name = "libvpx" %}
{% set version = "1.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://download.videolan.org/contrib/vpx/libvpx-{{ version }}.tar.gz
  sha256: 965e51c91ad9851e2337aebcc0f517440c637c506f3a03948062e3d5ea129a83
  patches:
    - simpler_configure.patch  # [win]

build:
  number: 4
  skip: True  # [not win]
  run_exports:
    # new so names and compatibility changes on minor version
    # https://abi-laboratory.pro/tracker/timeline/libvpx/
    - {{ pin_subpackage('libvpx', max_pin='x.x') }}


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make                  # [unix]
    - m2-make               # [win]
    - yasm
    # - autotools_clang_conda  # [win]
    - m2-coreutils           # [win]
    - m2-bash                # [win]
    - m2-patch               # [win]
    - m2-sed                 # [win]
    - m2-gawk                # [win]
    - m2-perl                # [win]
    - m2-diffutils           # [win]
    - m2-grep                # [win]
    - perl                   # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/libvpx${SHLIB_EXT}
    - vpxenc --help  # [build_platform == target_platform]
    - vpxdec --help  # [build_platform == target_platform]

about:
  home: https://www.webmproject.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A high-quality, open video format for the web
  description: |
    libvpx is a free software video codec library from
    Google and the Alliance for Open Media (AOMedia).
    It serves as the reference software implementation for
    the video coding formats VP8 and VP9, and for AV1 a
    special fork named libaom that was stripped of
    backwards compatibility.
  doc_url: http://www.webmproject.org/vp9/
  dev_url: https://chromium.googlesource.com/webm/libvpx

extra:
  recipe-maintainers:
    - matthiasdiener
